/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/byerslights.glb --types --shadows 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber'
import Bulb from './Bulb'
import ClickableLetter from './ClickableLetter'

type GLTFResult = GLTF & {
  nodes: {
    Wall: THREE.Mesh
    Wires: THREE.Mesh
    Light102: THREE.Mesh
    Box: THREE.Mesh
    BulbHolders: THREE.Mesh
    LetterA: THREE.Mesh
    LetterB: THREE.Mesh
    LetterC: THREE.Mesh
    LetterD: THREE.Mesh
    LetterE: THREE.Mesh
    LetterF: THREE.Mesh
    LetterG: THREE.Mesh
    LetterH: THREE.Mesh
    LetterI: THREE.Mesh
    LetterJ: THREE.Mesh
    LetterK: THREE.Mesh
    LetterL: THREE.Mesh
    LetterM: THREE.Mesh
    LetterN: THREE.Mesh
    LetterO: THREE.Mesh
    LetterP: THREE.Mesh
    LetterQ: THREE.Mesh
    LetterR: THREE.Mesh
    LetterS: THREE.Mesh
    LetterT: THREE.Mesh
    LetterU: THREE.Mesh
    LetterV: THREE.Mesh
    LetterW: THREE.Mesh
    LetterX: THREE.Mesh
    LetterY: THREE.Mesh
    LetterZ: THREE.Mesh
    Light103: THREE.Mesh
    Light104: THREE.Mesh
    Light201: THREE.Mesh
    Light202: THREE.Mesh
    Light203: THREE.Mesh
    Light204: THREE.Mesh
    Light301: THREE.Mesh
    Light302: THREE.Mesh
    Light303: THREE.Mesh
    Light304: THREE.Mesh
    LightA: THREE.Mesh
    LightB: THREE.Mesh
    LightC: THREE.Mesh
    LightD: THREE.Mesh
    LightE: THREE.Mesh
    LightF: THREE.Mesh
    LightG: THREE.Mesh
    LightH: THREE.Mesh
    LightI: THREE.Mesh
    LightJ: THREE.Mesh
    LightK: THREE.Mesh
    LightL: THREE.Mesh
    LightM: THREE.Mesh
    LightN: THREE.Mesh
    LightO: THREE.Mesh
    LightP: THREE.Mesh
    LightQ: THREE.Mesh
    LightR: THREE.Mesh
    LightS: THREE.Mesh
    LightT: THREE.Mesh
    LightU: THREE.Mesh
    LightV: THREE.Mesh
    LightW: THREE.Mesh
    LightX: THREE.Mesh
    LightY: THREE.Mesh
    LightZ: THREE.Mesh
    BulbHolders002: THREE.Mesh
    BulbHolders003: THREE.Mesh
    BulbHolders004: THREE.Mesh
    BulbHolders005: THREE.Mesh
    BulbHolders006: THREE.Mesh
    BulbHolders007: THREE.Mesh
    BulbHolders008: THREE.Mesh
    BulbHolders009: THREE.Mesh
    BulbHolders010: THREE.Mesh
    BulbHolders011: THREE.Mesh
    BulbHolders012: THREE.Mesh
    BulbHolders013: THREE.Mesh
    BulbHolders014: THREE.Mesh
    BulbHolders015: THREE.Mesh
    BulbHolders016: THREE.Mesh
    BulbHolders017: THREE.Mesh
    BulbHolders018: THREE.Mesh
    BulbHolders019: THREE.Mesh
    BulbHolders020: THREE.Mesh
    BulbHolders021: THREE.Mesh
    BulbHolders022: THREE.Mesh
    BulbHolders023: THREE.Mesh
    BulbHolders024: THREE.Mesh
    BulbHolders025: THREE.Mesh
    BulbHolders026: THREE.Mesh
    BulbHolders027: THREE.Mesh
    BulbHolders028: THREE.Mesh
    BulbHolders029: THREE.Mesh
    BulbHolders030: THREE.Mesh
    BulbHolders031: THREE.Mesh
    BulbHolders032: THREE.Mesh
    BulbHolders033: THREE.Mesh
    BulbHolders034: THREE.Mesh
    BulbHolders035: THREE.Mesh
    BulbHolders036: THREE.Mesh
    BulbHolders037: THREE.Mesh
    Light101: THREE.Mesh
    BulbHolders001: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    Wire: THREE.MeshStandardMaterial
    bluelight: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    Text: THREE.MeshStandardMaterial
    greenlight: THREE.MeshStandardMaterial
    redlight: THREE.MeshStandardMaterial
    yellowlight: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

interface ModelProps {
  activeLetter: string | null;
  onLetterClick?: (letter: string) => void;
}


export function Model({ activeLetter,onLetterClick, ...props }: ThreeElements['group'] & ModelProps) {
  const { nodes, materials } = useGLTF('/byerslights.glb') as unknown as GLTFResult
  const isLit = (letter: string) => activeLetter === letter;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Wall.geometry} material={materials.Material} position={[-0.209, 0.036, 0]} rotation={[0, 0, Math.PI]} scale={[1, 1.925, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Wires.geometry} material={materials.Wire} position={[2.175, 0.592, -0.189]} />
 
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders.geometry} material={materials.Wire} material-color={"black"} position={[-0.282, -0.425, -0.171]} />

      <ClickableLetter 
      letter="A"
      onClick={onLetterClick}
      geometry={nodes.LetterA.geometry} 
      material={materials.Text} 
      position={[-1.503, 0.245, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.57} 
    />
      <ClickableLetter 
      letter="B"
      onClick={onLetterClick}
      geometry={nodes.LetterB.geometry} 
      material={materials.Text} 
      position={[-1.119, 0.238, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.656} 
    />

    <ClickableLetter 
      letter="C"
      onClick={onLetterClick}
      geometry={nodes.LetterC.geometry} 
      material={materials.Text} 
      position={[-0.798, 0.281, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.656} 
    />

    <ClickableLetter 
      letter="D"
      onClick={onLetterClick}
      geometry={nodes.LetterD.geometry} 
      material={materials.Text} 
      position={[-0.441, 0.274, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.588} 
    />

    <ClickableLetter 
      letter="E"
      onClick={onLetterClick}
      geometry={nodes.LetterE.geometry} 
      material={materials.Text} 
      position={[-0.044, 0.317, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.588} 
    />

    <ClickableLetter 
      letter="F"
      onClick={onLetterClick}
      geometry={nodes.LetterF.geometry} 
      material={materials.Text} 
      position={[0.299, 0.353, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.588} 
    />

    <ClickableLetter 
      letter="G"
      onClick={onLetterClick}
      geometry={nodes.LetterG.geometry} 
      material={materials.Text} 
      position={[0.67, 0.351, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.588} 
    />

    <ClickableLetter 
      letter="H"
      onClick={onLetterClick}
      geometry={nodes.LetterH.geometry} 
      material={materials.Text} 
      position={[1.101, 0.332, -0.198]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.537} 
    />

    <ClickableLetter 
      letter="I"
      onClick={onLetterClick}
      geometry={nodes.LetterI.geometry} 
      material={materials.Text} 
      position={[-1.821, -0.302, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="J"
      onClick={onLetterClick}
      geometry={nodes.LetterJ.geometry} 
      material={materials.Text} 
      position={[-1.486, -0.311, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="K"
      onClick={onLetterClick}
      geometry={nodes.LetterK.geometry} 
      material={materials.Text} 
      position={[-1.115, -0.321, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="L"
      onClick={onLetterClick}
      geometry={nodes.LetterL.geometry} 
      material={materials.Text} 
      position={[-0.753, -0.296, -0.194]} 
      rotation={[Math.PI / 2, 0, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="M"
      onClick={onLetterClick}
      geometry={nodes.LetterM.geometry} 
      material={materials.Text} 
      position={[-0.519, -0.184, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="N"
      onClick={onLetterClick}
      geometry={nodes.LetterN.geometry} 
      material={materials.Text} 
      position={[-0.055, -0.126, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="O"
      onClick={onLetterClick}
      geometry={nodes.LetterO.geometry} 
      material={materials.Text} 
      position={[0.326, -0.169, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="P"
      onClick={onLetterClick}
      geometry={nodes.LetterP.geometry} 
      material={materials.Text} 
      position={[0.775, -0.233, -0.194]} 
      rotation={[Math.PI / 2, 0.094, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="Q"
      onClick={onLetterClick}
      geometry={nodes.LetterQ.geometry} 
      material={materials.Text} 
      position={[1.158, -0.208, -0.194]} 
      rotation={[Math.PI / 2, -0.019, 0]} 
      scale={0.409} 
    />

    <ClickableLetter 
      letter="R"
      onClick={onLetterClick}
      geometry={nodes.LetterR.geometry} 
      material={materials.Text} 
      position={[-1.821, -0.761, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="S"
      onClick={onLetterClick}
      geometry={nodes.LetterS.geometry} 
      material={materials.Text} 
      position={[-1.432, -0.785, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.747} 
    />

    <ClickableLetter 
      letter="T"
      onClick={onLetterClick}
      geometry={nodes.LetterT.geometry} 
      material={materials.Text} 
      position={[-1.158, -0.853, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="U"
      onClick={onLetterClick}
      geometry={nodes.LetterU.geometry} 
      material={materials.Text} 
      position={[-0.772, -0.822, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="V"
      onClick={onLetterClick}
      geometry={nodes.LetterV.geometry} 
      material={materials.Text} 
      position={[-0.406, -0.723, -0.194]} 
      rotation={[Math.PI / 2, 0.067, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="W"
      onClick={onLetterClick}
      geometry={nodes.LetterW.geometry} 
      material={materials.Text} 
      position={[0.041, -0.712, -0.194]} 
      rotation={[Math.PI / 2, 0.072, 0]} 
      scale={0.678} 
    />

    <ClickableLetter 
      letter="X"
      onClick={onLetterClick}
      geometry={nodes.LetterX.geometry} 
      material={materials.Text} 
      position={[0.47, -0.647, -0.194]} 
      rotation={[Math.PI / 2, 0.029, 0]} 
      scale={0.661} 
    />

    <ClickableLetter 
      letter="Y"
      onClick={onLetterClick}
      geometry={nodes.LetterY.geometry} 
      material={materials.Text} 
      position={[0.886, -0.667, -0.194]} 
      rotation={[Math.PI / 2, 0.184, 0]} 
      scale={0.57} 
    />

    <ClickableLetter 
      letter="Z"
      onClick={onLetterClick}
      geometry={nodes.LetterZ.geometry} 
      material={materials.Text} 
      position={[1.225, -0.69, -0.194]} 
      rotation={[Math.PI / 2, -0.092, 0]} 
      scale={0.57} 
    />

      {/* Light101 - Green */}
      <Bulb 
        geometry={nodes.Light101.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={false}
        position={[-1.927, 0.698, -0.176]} rotation={[0, 0, 2.695]} scale={0.018} 
      />

      {/* Light102 - Blue */}
      <Bulb 
        geometry={nodes.Light102.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={false}
        position={[-1.619, 0.588, -0.164]} 
        rotation={[-0.549, 0.314, -2.746]} 
        scale={0.018} 
      />
      {/* Light103 - Green */}
      <Bulb 
        geometry={nodes.Light103.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={false}
        position={[1.583, 0.612, -0.187]} 
        rotation={[-2.861, -0.796, 0.627]} 
        scale={0.018} 
      />

      {/* Light104 - Blue */}
      <Bulb 
        geometry={nodes.Light104.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={false}
        position={[1.819, 0.682, -0.193]} 
        rotation={[-0.204, 0.56, -2.635]} 
        scale={0.018} 
      />

      {/* Light201 - Blue */}
      <Bulb 
        geometry={nodes.Light201.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={false}
        position={[-2.319, 0.202, -0.176]} 
        rotation={[0, 0, 2.715]} 
        scale={0.018} 
      />

      {/* Light202 - Green */}
      <Bulb 
        geometry={nodes.Light202.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={false}
        position={[-2.052, 0.111, -0.176]} 
        rotation={[0, 0, 3.125]} 
        scale={0.018} 
      />

      {/* Light203 - Green */}
      <Bulb 
        geometry={nodes.Light203.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={false}
        position={[1.591, 0.052, -0.17]} 
        rotation={[2.41, 0.571, 0.686]} 
        scale={0.018} 
      />

      {/* Light204 - Red */}
      <Bulb 
        geometry={nodes.Light204.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={false}
        position={[1.838, 0.142, -0.169]} 
        rotation={[2.303, -0.358, 1.534]} 
        scale={0.018} 
      />

      {/* Light301 - Yellow */}
      <Bulb 
        geometry={nodes.Light301.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={false}
        position={[-2.327, -0.242, -0.176]} 
        rotation={[0, 0, 2.715]} 
        scale={0.018} 
      />

      {/* Light302 - Red */}
      <Bulb 
        geometry={nodes.Light302.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={false}
        position={[-1.937, -0.367, -0.192]} 
        rotation={[2.491, 0.78, 0.585]} 
        scale={0.018} 
      />

      {/* Light303 - Blue */}
      <Bulb 
        geometry={nodes.Light303.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={false}
        position={[1.791, -0.262, -0.164]} 
        rotation={[0.68, -0.744, -1.844]} 
        scale={0.018} 
      />

      {/* Light304 - Green */}
      <Bulb 
        geometry={nodes.Light304.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={false}
        position={[2.012, -0.128, -0.169]} 
        rotation={[2.284, 0.293, 0.984]} 
        scale={0.018} 
      />

      <Bulb 
        geometry={nodes.LightA.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('A')}
        position={[-1.327, 0.542, -0.16]} rotation={[-0.532, 0.114, 2.726]} scale={0.018} 
      />

      <Bulb 
        geometry={nodes.LightB.geometry} 
        baseMaterial={materials.yellowlight} 
        color="green" 
        isActive={isLit('B')}
        position={[-1.015, 0.571, -0.159]} rotation={[-1.559, 0.95, -2.192]} scale={0.018} 
      />

      <Bulb 
        geometry={nodes.LightC.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('C')}
        position={[-0.656, 0.593, -0.174]} rotation={[3.003, 0.582, -0.063]} scale={0.018} 
      />
      <Bulb 
        geometry={nodes.LightD.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('D')}
        position={[-0.259, 0.573, -0.17]} rotation={[2.488, -0.512, -0.431]} scale={0.018} 
      />
      <Bulb 
        geometry={nodes.LightE.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={isLit('E')}
        position={[0.106, 0.596, -0.165]} rotation={[2.271, 0.11, 0.087]} scale={0.018} 
      />

      <Bulb 
        geometry={nodes.LightF.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('F')}
        position={[0.423, 0.632, -0.187]} rotation={[3, -0.228, -0.538]} scale={0.018} 
      />
      <Bulb 
        geometry={nodes.LightG.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('G')}
        position={[0.811, 0.634, -0.19]} rotation={[-3.073, -0.209, 0.393]} scale={0.018} 
      />
      <Bulb 
        geometry={nodes.LightH.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('H')}
        position={[1.254, 0.595, -0.183]} rotation={[-0.231, -0.631, -2.963]} scale={0.018} 
      />

      <Bulb 
        geometry={nodes.LightI.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('I')}
        position={[-1.642, -0.01, -0.176]} rotation={[0, 0, -2.63]} scale={0.018} 
      />

      {/* J - Red */}
      <Bulb 
        geometry={nodes.LightJ.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('J')}
        position={[-1.32, -0.034, -0.169]} 
        rotation={[-1.914, 0.725, -1.643]} 
        scale={0.018} 
      />

      {/* K - Blue */}
      <Bulb 
        geometry={nodes.LightK.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={isLit('K')}
        position={[-0.998, -0.045, -0.172]} 
        rotation={[-0.771, -0.493, 2.266]} 
        scale={0.018} 
      />

      {/* L - Yellow */}
      <Bulb 
        geometry={nodes.LightL.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('L')}
        position={[-0.645, 0.02, -0.163]} 
        rotation={[-1.14, -0.845, 2.506]} 
        scale={0.018} 
      />

      {/* M - Green */}
      <Bulb 
        geometry={nodes.LightM.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('M')}
        position={[-0.322, 0.105, -0.173]} 
        rotation={[-0.596, 0.862, -2.573]} 
        scale={0.018} 
      />

      {/* N - Yellow */}
      <Bulb 
        geometry={nodes.LightN.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('N')}
        position={[0.057, 0.179, -0.166]} 
        rotation={[-0.839, -0.681, 2.613]} 
        scale={0.018} 
      />

      {/* O - Red */}
      <Bulb 
        geometry={nodes.LightO.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('O')}
        position={[0.478, 0.121, -0.171]} 
        rotation={[-1.257, -1.234, 2.081]} 
        scale={0.018} 
      />

      {/* P - Yellow */}
      <Bulb 
        geometry={nodes.LightP.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('P')}
        position={[0.922, 0.033, -0.178]} 
        rotation={[-0.762, -0.454, 2.776]} 
        scale={0.018} 
      />

      {/* Q - Blue */}
      <Bulb 
        geometry={nodes.LightQ.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={isLit('Q')}
        position={[1.307, 0.04, -0.178]} 
        rotation={[-3.017, 0.063, -0.217]} 
        scale={0.018} 
      />

      {/* R - Green */}
      <Bulb 
        geometry={nodes.LightR.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('R')}
        position={[-1.667, -0.45, -0.18]} 
        rotation={[2.507, -0.777, -0.478]} 
        scale={0.018} 
      />

      {/* S - Blue */}
      <Bulb 
        geometry={nodes.LightS.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={isLit('S')}
        position={[-1.319, -0.524, -0.172]} 
        rotation={[3.027, 0.899, 0.18]} 
        scale={0.018} 
      />

      {/* T - Red */}
      <Bulb 
        geometry={nodes.LightT.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('T')}
        position={[-1.019, -0.536, -0.161]} 
        rotation={[2.181, -0.687, -0.628]} 
        scale={0.018} 
      />

      {/* U - Yellow */}
      <Bulb 
        geometry={nodes.LightU.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('U')}
        position={[-0.657, -0.496, -0.161]} 
        rotation={[2.031, 0.069, -1.08]} 
        scale={0.018} 
      />

      {/* V - Green */}
      <Bulb 
        geometry={nodes.LightV.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('V')}
        position={[-0.299, -0.441, -0.17]} 
        rotation={[1.214, 0.751, 1.78]} 
        scale={0.018} 
      />

      {/* W - Blue */}
      <Bulb 
        geometry={nodes.LightW.geometry} 
        baseMaterial={materials.bluelight} 
        color="blue" 
        isActive={isLit('W')}
        position={[0.243, -0.321, -0.17]} 
        rotation={[-1.273, -0.516, -1.461]} 
        scale={0.018} 
      />

      {/* X - Red */}
      <Bulb 
        geometry={nodes.LightX.geometry} 
        baseMaterial={materials.redlight} 
        color="red" 
        isActive={isLit('X')}
        position={[0.628, -0.378, -0.172]} 
        rotation={[0.99, 1.067, 1.862]} 
        scale={0.018} 
      />

      {/* Y - Green */}
      <Bulb 
        geometry={nodes.LightY.geometry} 
        baseMaterial={materials.greenlight} 
        color="green" 
        isActive={isLit('Y')}
        position={[0.989, -0.385, -0.171]} 
        rotation={[-2.934, 1.365, -0.515]} 
        scale={0.018} 
      />

      {/* Z - Yellow */}
      <Bulb 
        geometry={nodes.LightZ.geometry} 
        baseMaterial={materials.yellowlight} 
        color="yellow" 
        isActive={isLit('Z')}
        position={[1.418, -0.371, -0.166]} 
        rotation={[0.38, -0.676, -1.94]} 
        scale={0.018} 
      />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders002.geometry} material={materials.Wire} position={[-1.627, 0.608, -0.173]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders003.geometry} material={materials.Wire} position={[-1.317, 0.56, -0.172]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders004.geometry} material={materials.Wire} position={[-1.026, 0.587, -0.172]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders005.geometry} material={materials.Wire} position={[-0.658, 0.616, -0.178]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders006.geometry} material={materials.Wire} position={[-0.268, 0.593, -0.179]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders007.geometry} material={materials.Wire} position={[0.108, 0.611, -0.183]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders008.geometry} material={materials.Wire} position={[0.411, 0.652, -0.187]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders009.geometry} material={materials.Wire} position={[0.82, 0.656, -0.19]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders010.geometry} material={materials.Wire} position={[1.251, 0.617, -0.191]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders011.geometry} material={materials.Wire} position={[1.593, 0.633, -0.191]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders012.geometry} material={materials.Wire} position={[1.809, 0.703, -0.191]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders013.geometry} material={materials.Wire} position={[-1.653, 0.01, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders014.geometry} material={materials.Wire} position={[-1.338, -0.02, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders015.geometry} material={materials.Wire} position={[-0.982, -0.028, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders016.geometry} material={materials.Wire} position={[-0.636, 0.038, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders017.geometry} material={materials.Wire} position={[-0.33, 0.127, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders018.geometry} material={materials.Wire} position={[0.066, 0.199, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders019.geometry} material={materials.Wire} position={[0.485, 0.143, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders020.geometry} material={materials.Wire} position={[0.93, 0.051, -0.191]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders021.geometry} material={materials.Wire} position={[1.302, 0.063, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders022.geometry} material={materials.Wire} position={[1.604, 0.071, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders023.geometry} material={materials.Wire} position={[1.86, 0.137, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders024.geometry} material={materials.Wire} position={[-1.316, -0.5, -0.171]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders025.geometry} material={materials.Wire} position={[-1.674, -0.428, -0.186]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders026.geometry} material={materials.Wire} position={[-1.927, -0.346, -0.197]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders027.geometry} material={materials.Wire} position={[-2.052, 0.135, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders028.geometry} material={materials.Wire} position={[-2.309, 0.223, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders029.geometry} material={materials.Wire} position={[-2.317, -0.22, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders030.geometry} material={materials.Wire} position={[-1.03, -0.518, -0.172]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders031.geometry} material={materials.Wire} position={[-0.677, -0.493, -0.172]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders032.geometry} material={materials.Wire} position={[0.222, -0.333, -0.171]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders033.geometry} material={materials.Wire} position={[0.639, -0.358, -0.177]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders034.geometry} material={materials.Wire} position={[0.987, -0.362, -0.178]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders035.geometry} material={materials.Wire} position={[1.401, -0.358, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders036.geometry} material={materials.Wire} position={[1.774, -0.247, -0.171]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders037.geometry} material={materials.Wire} position={[2.031, -0.115, -0.176]} />
      <mesh castShadow receiveShadow geometry={nodes.BulbHolders001.geometry} material={materials.Wire} position={[-0.266, -0.409, -0.172]} rotation={[1.214, 0.751, 1.78]} scale={0.015} />
    </group>
  )
}

useGLTF.preload('/byerslights.glb')
